spring:
  datasource:
    driverClassName: org.h2.Driver
    jpa:
      spring:
        jpa:
          database-platform: org.hibernate.dialect.H2Dialect
    username: tjms
    password: 123456
    url: jdbc:h2:mem:servidores
  flyway:
    user: tjms
    password: 123456
    locations: filesystem:db/migration
    url: jdbc:h2:mem:servidores
  h2:
    console:
      enabled: 'true'
